name: moviesplus
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  card_swiper: ^3.0.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.11
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  image: assets/app/icon-splash.png
  color: "#1F1D2B"

  android_12:
    image: assets/app/icon-splash.png
    color: "#1F1D2B"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - assets/icons/
    - assets/app/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
